project:
  type: website

website:
  search:
    location: navbar
    type: overlay
  favicon: images/Joaquin.jpeg
  title: "Portfolio"
  navbar:
    left:  
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Industry & Research Experience
      - href: projects.qmd
        text: Class Projects
      - href: e155.qmd
        text: Microprocessors Projects 
      - href: personal.qmd
        text: Personal Projects
      - href: pcb.qmd
        text: PCB Designs
      - href: publications.qmd
        text: Publications & Reports
      - href: resources.qmd
        text: Resources
      - href: blog.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/jgonzalezsalgado
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/joaquin-e-gs/
        target: _blank  


format:
  html:
    theme:
      light:
      - cosmo
      - brand
      dark: darkly
    css: styles.css
    toc: true
    
